### ISSUE TITLE
glBindFrameBuffer missing

### ISSUE THREAD

**Issue by wasabia** [FlutterGL/opengl_es_bindings#1]
Hi!

seems this plugin miss glBindFrameBuffer ?

**Comment by escamoteur** [comment]
can't be, because I use in in the FlutterWebGL package

**Comment by wasabia** [comment]
sorry buffer should be lowercase  ->  glBindFramebuffer

**Comment by wasabia** [comment]
my fault

**Comment by escamoteur** [comment]
I recommend using the FlutterWebGL package
